server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RamFernando/spring-cloud-config-store
#          username: RamFernando
          search-paths:
            - '*service'
#          repos:
