spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allocationdb?createDatabaseIfNotExist=true
    username: newuser
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update